export const CREATE_ORDER = 'CREATE_ORDER';
export const SET_PERSONAL_DETAILS = 'ADD_PERSONAL_DETAILS';
export const SET_LOCATION_DETAILS = 'ADD_LOCATION_DETAILS';

export const LOGIN = 'LOGIN';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const GET_PROFILE = 'GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';