// Authentication - Log In
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';

// Authentication - Sign Up
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'FAILED';
export const SIGN_UP_COMPLETE = 'FAILED';

// Authentication - Common
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS ';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const GET_PROFILE_COMPLETE = 'GET_PROFILE_COMPLETE';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_AVAILABILITY = 'SET_AVAILABILITY';

// Address
export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_ERROR = 'GET_ADDRESS_ERROR';
export const GET_ADDRESS_COMPLETE = 'GET_ADDRESS_COMPLETE';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_ADDRESS_SUCCESS = 'SET_ADDRESS_SUCCESS';
export const SET_ADDRESS_ERROR = 'SET_ADDRESS_ERROR';
export const SET_ADDRESS_COMPLETE = 'SET_ADDRESS_COMPLETE';

// Order
export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR';
export const PLACE_ORDER_COMPLETE = 'PLACE_ORDER_COMPLETE';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

// Preferences
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const GET_PREFERENCES_COMPLETE = 'GET_PREFERENCES_COMPLETE';
export const SET_PREFERENCES = 'SET_PREFERENCES';
export const SET_PREFERENCES_COMPLETE = 'SET_PREFERENCES_COMPLETE';

// Payment Card
export const SET_PAYMENT_CARD = 'SET_PAYMENT_CARD';
export const SET_PAYMENT_CARD_SUCCESS = 'SET_PAYMENT_CARD_SUCCESS';
export const SET_PAYMENT_CARD_ERROR = 'SET_PAYMENT_CARD_ERROR';
export const SET_PAYMENT_CARD_COMPLETE = 'SET_PAYMENT_CARD_COMPLETE';
export const GET_PAYMENT_CARD = 'GET_PAYMENT_CARD';
export const GET_PAYMENT_CARD_SUCCESS = 'GET_PAYMENT_CARD_SUCCESS';
export const GET_PAYMENT_CARD_ERROR = 'GET_PAYMENT_CARD_ERROR';
export const GET_PAYMENT_CARD_COMPLETE = 'GET_PAYMENT_CARD_COMPLETE';

// Pricing - user
export const GET_USER_PRICING = 'GET_USER_PRICING';
export const GET_USER_PRICING_SUCCESS = 'GET_USER_PRICING_SUCCESS';
export const GET_USER_PRICING_ERROR = 'GET_USER_PRICING_ERROR';
export const GET_USER_PRICING_COMPLETE = 'GET_USER_PRICING_COMPLETE';

// Pricing - postal code
export const GET_POSTAL_CODE_PRICING = 'GET_POSTAL_CODE_PRICING';
export const GET_POSTAL_CODE_PRICING_SUCCESS = 'GET_POSTAL_CODE_PRICING_SUCCESS';
export const GET_POSTAL_CODE_PRICING_ERROR = 'GET_POSTAL_CODE_PRICING_ERROR';
export const GET_POSTAL_CODE_PRICING_COMPLETE = 'GET_POSTAL_CODE_PRICING_COMPLETE';
