// Authentication
export const LOGIN = 'LOGIN';
export const SIGN_UP = 'SIGN_UP';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_ADDRESS = 'SET_ADDRESS';

// Order
export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR';
export const PLACE_ORDER_COMPLETE = 'PLACE_ORDER_COMPLETE';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

// Preferences
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const GET_PREFERENCES_COMPLETE = 'GET_PREFERENCES_COMPLETE';
export const SET_PREFERENCES = 'SET_PREFERENCES';
export const SET_PREFERENCES_COMPLETE = 'SET_PREFERENCES_COMPLETE';