export const SERVICE_AVAILABILITY_UNKNOWN = 'SERVICE_AVAILABILITY_UNKNOWN';
export const NOT_AVAILABLE = 'NOT_AVAILABLE';
export const WASH_FOLD_DRY_CLEANING_AVAILABLE = 'WASH_FOLD_DRY_CLEANING_AVAILABLE';
export const ONLY_WASH_FOLD_AVAILABLE = 'ONLY_WASH_FOLD_AVAILABLE';
export const ONLY_DRY_CLEANING_AVAILABLE = 'ONLY_DRY_CLEANING_AVAILABLE';

export const SERVICE_AVAILABLE_STATES = new Set([
  WASH_FOLD_DRY_CLEANING_AVAILABLE,
  ONLY_WASH_FOLD_AVAILABLE,
  ONLY_DRY_CLEANING_AVAILABLE
]);
